version: 0.2

env:
  variables:
    S3_BUCKET: vpc-lab-1712
    TASKCAT_OUTPUT: vpc-lab-1712-taskcat

phases:
  install:
    commands:
      - pip install cfn-lint==1.35.4 taskcat==0.9.57

  pre_build:
    on-failure: ABORT
    commands:
      - cfn-lint ec2/*.yaml nat/*.yaml route_table/*.yaml security_group/*.yaml vpc/*.yaml codepipeline.yaml root.yaml

  build:
    on-failure: ABORT
    commands:
      - mkdir -p temp_upload
      - cp -r ec2 nat route_table security_group vpc temp_upload/
      - cp root.yaml temp_upload/
      - aws s3 sync temp_upload/ s3://$S3_BUCKET --delete
      - taskcat test run
    finally:
      - aws s3 sync taskcat_outputs/ s3://$TASKCAT_OUTPUT/outputs --acl public-read --delete

artifacts:
  name: templates
  files:
    - root.yaml
  base-directory: temp_upload
