version: 0.2

env:
  variables:
    S3_BUCKET: vpc-lab-1712
    TASKCAT_OUTPUT: vpc-lab-1712-taskcat

phases:
  install:
    commands:
      - pip install cfn-lint==1.35.4 taskcat==0.9.57

  pre_build:
    on-failure: ABORT
    commands:
      - |
        set +e
        cfn-lint ec2/ec2.yaml nat/nat.yaml route_table/route_table.yaml security_group/security_group.yaml vpc/vpc.yaml codepipeline.yaml root.yaml
        set -e


  build:
    on-failure: ABORT
    commands:
      - mkdir -p temp_upload
      - cp -r ec2 nat route_table security_group vpc temp_upload/
      - cp root.yaml temp_upload/
      - aws s3 sync temp_upload/ s3://$S3_BUCKET --delete
      - taskcat test run

artifacts:
  name: templates
  files:
    - root.yaml
  base-directory: temp_upload
